-- Tạo Enum
CREATE TYPE GIOI_TINH AS ENUM ('NAM', 'NU');
CREATE TYPE VAITRO_DOCGIA AS ENUM ('DOCGIA');
-- CREATE TYPE TRANGTHAI_DOCGIA AS ENUM ('HOATDONG', 'TAMKHOA', 'CAM');
CREATE TYPE TRANGTHAI_MUON AS ENUM ('CHODUYET', 'DADUYET', 'TUCHOI', 'DATRA', 'DANGMUON');
-- CREATE TYPE TRANGTHAI_DONHANG AS ENUM ('DANGXULY', 'DAGIAO', 'DAHUY', 'GIAOTHATBAI');
-- CREATE TYPE VAITRO_NHANVIEN AS ENUM ('THUTHU', 'QUANLY', 'NHANVIEN', 'ADMIN');
-- CREATE TYPE TRANGTHAI_NHANVIEN AS ENUM ('HOATDONG', 'NGHI', 'KHOA');
CREATE TYPE LOAITHONGBAO AS ENUM ('SAPTOIHAN', 'QUAHAN', 'DATRASACH', 'DADUYET');
